### ISSUE TITLE
Mandatory Description

### ISSUE THREAD

**Issue by Semir1212** [humhub/polls#107]
Currently adding a description is required to create a poll, that should not be the case. Additionally, there is currently no error message indicating this.

If the description is supposed to stay mandatory, at least an error message should be added.

**Comment by yurabakhtin** [comment]
@luke- I see the error message "Description cannot be blank." when submit an empty form:

![poll_empty](https://user-images.githubusercontent.com/6995524/197950025-8c4b96b4-1680-450b-9588-9b1e28fd25d3.png)

If I remember correctly there is no field "Question" in old version, we had only "Description", then we added the "Question" field and kept the old field "Description" mandatory as it was before.

So please confirm if we really need to make the field "Question" as mandatory instead of the field "Descripiton", thanks.

**Comment by Semir1212** [comment]
@yurabakhtin In my test environment these error messages do not appear, but I can remember that they used to exist, now that I see your screenshot. 

The description being mandatory and the question itself being not makes even less sense. I would reverse this behaviour. @luke-

**Comment by luke-** [comment]
@Semir1212 The problem here is, the "Question" field is newly added. I.e. there is already content without this field filled in.

But for new polls I would definitely make Question mandatory and Description optional.

**Comment by yurabakhtin** [comment]
@luke- 

> But for new polls I would definitely make Question mandatory and Description optional.

Do you mean for new version we should make Question mandatory and Description optional?
Or do you mean to detect someshow what poll is old and what poll is new and make it only for new polls?
However I am not sure how it is possible to find what poll is old, so we can do this for all polls, do you agree this change?

**Comment by luke-** [comment]
- Yes, Question mandatory and description optional. If someone edit's an old Poll, he needs to enter a Question.

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub/polls/pull/108.
