### ISSUE TITLE
Add REST API Support

### ISSUE THREAD

**Issue by luke-** [humhub/polls#86]
https://github.com/humhub/rest/issues/33

**Comment by yurabakhtin** [comment]
@luke- I have implemented all endpoints in PR https://github.com/humhub/polls/pull/89, it works and can be merged but I think it would be better firstly to create API tests and create a doc in the `rest` module.

**Comment by luke-** [comment]
@yurabakhtin Ok, can you create the tests & docs?

**Comment by yurabakhtin** [comment]
@luke- Yes, sure.

**Comment by yurabakhtin** [comment]
@luke- Tests have been created in the commit https://github.com/humhub/polls/pull/89/commits/da89a3bbabd11e8d7a91f89d12d2485b319e3929, and the PR can be merged because docs will be updated in the module "rest" here https://github.com/humhub/rest/tree/master/docs.x

**Comment by luke-** [comment]
@yurabakhtin Thank you! Aren't module related REST API docs always in the module repository? Like here: 
https://github.com/humhub/calendar/tree/master/docs/swagger

**Comment by yurabakhtin** [comment]
@luke- 

> Aren't module related REST API docs always in the module repository? Like here:
https://github.com/humhub/calendar/tree/master/docs/swagger

Yes, you are right, I forgot about this, ok I copied the docs into the module "polls" here https://github.com/humhub/polls/pull/89/commits/b6293387d2aab6dd7a2dac90d0bc173ef086c8f3, because firstly I added if in the rest module PR https://github.com/humhub/rest/pull/64, please note even if we have the docs inside each module separately we also have then inside rest module as copy.

Also only in the rest module we have the postman collection file which I updated in the new PR https://github.com/humhub/rest/pull/64 so it would be good to merge the PR as well.

**Comment by luke-** [comment]
@yurabakhtin  It is ok to have a complete PostMan file in the Rest module. But I would prefer not to have the Polls Swagger Doc in the Rest module again. That only gives confusion and one always forgets to adjust one Swagger file.

**Comment by yurabakhtin** [comment]
@luke- Do you mean to remove all swagger files from the rest module if they already exist in the separate module?

**Comment by luke-** [comment]
@yurabakhtin Yes, I would like to prevent duplicates. From the rest module we link to the available files anyway: https://github.com/humhub/rest/blob/master/docs/MANUAL.md

**Comment by yurabakhtin** [comment]
@luke- Ok, I updated the manual doc and removed the docs of the external modules in commit https://github.com/humhub/rest/pull/64/commits/a61d1448aa87da49286ab770c673c7dd04fdac88.

**Comment by luke-** [comment]
@yurabakhtin Thanks!
